apiVersion: v1
kind: Secret
metadata:
  name: {{ include "saas-workspace.fullname" . }}-secret
  labels:
    {{- include "saas-workspace.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
