apiVersion: v1
kind: Service
metadata:
  name: {{ include "saas-workspace.fullname" . }}-backend
  labels:
    {{- include "saas-workspace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.backend.type }}
  selector:
    app: backend
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
